#===============================================================================================================
#     __  __               _    _        ____          _    _    _        _____                        _
#    |  \/  |             | |  (_)      |  _ \        | |  | |  | |      |  __ \                      | |
#    | \  / |  ___   _ __ | |_  _  ___  | |_) |  __ _ | |_ | |_ | |  ___ | |__) |  ___   _   _   __ _ | |  ___
#    | |\/| | / _ \ | '__|| __|| |/ __| |  _ <  / _` || __|| __|| | / _ \|  _  /  / _ \ | | | | / _` || | / _ \
#    | |  | || (_) || |   | |_ | |\__ \ | |_) || (_| || |_ | |_ | ||  __/| | \ \ | (_) || |_| || (_| || ||  __/
#    |_|  |_| \___/ |_|    \__||_||___/ |____/  \__,_| \__| \__||_| \___||_|  \_\ \___/  \__, | \__,_||_| \___|
#                                                                                        __/ |
#                                                                                       |___/
#===============================================================================================================
# Mortis BattleRoyale v1.3.4 Plugin Configuration
# Spigot https://www.spigotmc.org/resources/✨mortis-battle-royale✨-loot-survive-fight-be-the-last-one-standing.113383/
# Github https://github.com/UnknownMysteryOfficial/Mortis-BattleRoyale
# Discord https://discord.gg/BZPepWZMFf
# Join discord for support
#======================================================#
#               BattleRoyale Settings                  #
#======================================================#
battleroyale:
  world-size: 500 # 500 means 500x500
  pvp-enabled-time: 60 # in seconds
  tp-world: "spawn" # this is the world where players will be teleported upon winning or leaving match.
#======================================================#
#               Resurgence Settings                    #
#======================================================#
resurgence:
  world-size: 200 # 200 means 200x200
  tp-world: "spawn" # this is the world where players will be teleported upon winning or leaving match.
#======================================================#
#               Restricted Commands                    #
#======================================================#
# Commands that are restricted while in the match world. (World names starting with battleroyale or resurgence are included as match world.)
restricted-commands:
  commands:
    - "tp"
    - "home"
    - "spawn"
    - "warp"